# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b7d1f21dc911fe9a6822cb3f673a341339f572a208454c82ec31b8b61c081987a15b8248032ecf55b29fd2c5e5b7556b7d63e4bec2cd498468179f4c223cbd3

test:
  secret_key_base: 9caf80d23bd7489ec5a035739d08eeb11076803e96959fc650949c53a2a65fba776765bffc269172929b29b6ef8888a39b613d39fd6dea49c9b3629d00045899

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
